### ISSUE TITLE
Installer (Y/N)

### ISSUE THREAD

**Issue by EliottFlapjack** [PBSK15/PBSK15#2]
Every time I try to write y or n it says "Please enter valid choice"

![Screenshot (451)](https://github.com/PBSK15/PBSK15/assets/168051288/8d94babd-a592-4407-b409-146a0cf4c8bb)

can someone explain what I'm doing wrong

**Comment by PBSK15** [comment]
Try putting in a capital "Y". I thought I made it disregard case (and looking back in the code it _should_), but right now that oddly doesn't seem to be the case.

**Comment by EliottFlapjack** [comment]
Oh don't worry I certainly tried every single combination, I tried: y, Y, yes, Yes, and YES

I have no idea why it's being so fussy

**Comment by PBSK15** [comment]
Hmmm. Have you restarted the installer and thus been encountering this issue again and again?

**Comment by EliottFlapjack** [comment]
Yep this happens every time I open it, the only thing I haven't tried is deleting it and reinstalling it

**Comment by PBSK15** [comment]
Would you mind recording a brief video of you opening the installer and normally continuing with the procedure up until this point? The primary reason I'm asking is because I noticed the window displays "Waiting for 0 seconds, press a key to continue...", which is an output of executing a command (`timeout` I think), and that shouldn't happen because the installer _should_ mute that. It could just be that I forgot to do that with that particular line, but I want to see if this effect protrudes throughout the entire installation process, and if that is true then that could lead us on the right track to fixing this.

**Comment by EliottFlapjack** [comment]
Sure I can do that, maybe not tonight but I can certainly do that

**Comment by PBSK15** [comment]
@EliottFlapjack Hold on, try this installer file real quick(I sent it as a ZIP becuase GitHub wouldn't let me send it as a BAT file). I removed a line that manually changed the character encoding of the script.,
[PBSK15InstallerWin.zip](https://github.com/PBSK15/PBSK15/files/15124892/PBSK15InstallerWin.zip)

**Comment by EliottFlapjack** [comment]
Same thing,

Uploading 2024-04-25 21-23-01-1.mp4…

**Comment by EliottFlapjack** [comment]
https://github.com/PBSK15/PBSK15/assets/168051288/d219be1e-391b-41eb-994a-44787741f739

**Comment by PBSK15** [comment]
Ok, I just realized the error. I feel very stupid lol. I reuploaded the installer to the original release/download page. Try it now, it should work.

**Comment by EliottFlapjack** [comment]
oh i see lol

**Comment by EliottFlapjack** [comment]
Ok well the installer now looks to be doing something, but after letting it do it's thing for a while, there doesn't seem to be any evidence that it actually installed anything except for git

**Comment by PBSK15** [comment]
Please open a separate issue so we can discuss this.
