### ISSUE TITLE
File not working correctly

### ISSUE THREAD

**Issue by EliottFlapjack** [PBSK15/PBSK15#5]
Some error code

https://github.com/PBSK15/PBSK15/assets/168051288/8100aae6-909a-4335-9b09-17aa44c46b5d

![Screenshot (453)](https://github.com/PBSK15/PBSK15/assets/168051288/d6794d31-c647-4781-a527-2b99674da05b)

**Comment by PBSK15** [comment]
What? Is Windows Defender deleting your files or something? Can you go to "C:/Program Files (x86)/", then go to the "PBSK15" folder's properties (by right clicking and clicking properties at the bottom), then send a picture of what the window says (after it's done updating/loading/enumerating everything)?

**Comment by EliottFlapjack** [comment]
![Screenshot (454)](https://github.com/PBSK15/PBSK15/assets/168051288/0b556be4-9f8e-42e7-87db-eb3114257a0b)
![Screenshot (455)](https://github.com/PBSK15/PBSK15/assets/168051288/b99e768d-b4a3-4169-b925-52f6f4fbf86e)
![Screenshot (456)](https://github.com/PBSK15/PBSK15/assets/168051288/fdd96dd8-ca68-4cf6-bd37-460196e5f259)

**Comment by PBSK15** [comment]
Can you zip "C:/Program Files (x86)/PBSK15/htdocs/vendor" and send it over? From the filesize alone it doesn't look like anything's wrong.

**Comment by EliottFlapjack** [comment]
👍
[vendor.zip](https://github.com/PBSK15/PBSK15/files/15135655/vendor.zip)

**Comment by PBSK15** [comment]
Uhhhh ok so apparently the issue is not with your current configuration, but with the ".gitignore" file in the repository, which blocks specific files (like user data) from accidentally being uploaded to the GitHub repository. The file was supposed to block the "cache" directory in the main PBSK15 folder, but it was miconfigured to the point where it would literally block all folders titled "cache" regardless of case, and it ended up not even uploading the "Cache" module of Twig (which is what the error was yelling about).

Also, thanks for heeding my warning. :)

**Comment by EliottFlapjack** [comment]
Any time lol

**Comment by PBSK15** [comment]
@EliottFlapjack I pushed the update to the repository fixing the issue, so just run PBSK15 again and it should automatically download the update (unless I made yet another really stupid error lol)

**Comment by EliottFlapjack** [comment]
Yippie you've done it my good sir, now I can be on the 2015 version of a website designed for toddlers when ever I want
![Screenshot (457)](https://github.com/PBSK15/PBSK15/assets/168051288/dc256902-108b-4dab-93bb-e26d559f4237)

**Comment by PBSK15** [comment]
@EliottFlapjack 👏👏👏👏👏👏👏👏👏
